### ISSUE TITLE
Materials not showing up properly

### ISSUE THREAD

**Issue by Nateliason** [if1live/unity-scene-web-exporter#1]
I'm having an issue with my materials showing up properly, it keeps coming out all black like this: 

http://screencast.com/t/bdFHdb9FCfv

I did the optional lightmapping and that didn't fix it, I also tried copying in one of your lights and that didn't change anything, which is why I think it has to do with the materials. 

I included a ZIP of my export, any idea what's going on? Thanks so much for making this!

[House.zip](https://github.com/if1live/unity-scene-web-exporter/files/575224/House.zip)

**Comment by Nateliason** [comment]
I think it might be the TGA file type for the materials, when I use JPGs it works. Does that sound right?

**Comment by Nateliason** [comment]
I replaced my Textures with JPGs and re-exported it worked fine!

**Comment by Nateliason** [comment]
Okay, different problem, though, if you update to A-Frame 0.3.0 all of the materials stop working :(

**Comment by Nateliason** [comment]
So a fix is to change the entity's into their respective shapes, e.g. `<a-box>` instead of `<a-entity>`, that seems to fix it

**Comment by goyusia** [comment]
@Nateliason I modify source to support a-frame v0.3.2. Could you try again?

**Comment by Nateliason** [comment]
Seems to work now, thanks!
