### ISSUE TITLE
A-frame exporter, exporting the room but when I open in firefox I don't see room just skye plane, snake vr image and logo image.

### ISSUE THREAD

**Issue by RYG81** [if1live/unity-scene-web-exporter#4]
Hi I am on Unity 5.6f1 and I tried to export the example scene 5minlab. I am not able to see lab room object in firefox or chrome or any other browser. I see only sky image plane, snake image plane and logo image plane.
Also is it possible to have unity interaction exported too? Like mouse click and drag and drop etc?

please help
rahul

**Comment by goyusia** [comment]
Now, this is feature. A-frame exporter supports only primitives.
When I develop it, three.js has stable version. but a-frame was not. 
A-frame was alpha version (v0.1 ~ v0.2)
Also, a-frame had unstable API. After release new version, many API are broken.
So, I didn't implement all features on a-frame.


Exporting unity script mean, exporting unity on web. I will not implement it.
If you want export unity project on web, you should find other project.
search keywords : unity, webvr
