### ISSUE TITLE
How to implement this into Unity Android Build?

### ISSUE THREAD

**Issue by Yuzuke** [if1live/unity-scene-web-exporter#5]
Hey there! I need to make an Android App with Unity, and that App can open a browser that scan AR target, thing is, A-Frame or three.js seems not working because it can't open Android device's camera.
I was desperately searching ways to solve this problem so if you feel disrupted plz ignore me...

**Comment by goyusia** [comment]
Sorry for late answer.

unity-scene-web-exporter export scene data, not scripting or logic.
unity-scene-web-exporter is based on A-Frame or three.js.
If A-Frame or three.js can't solve your problem, then unity-scene-web-exporter can't solve problem.

You should search other solution. some search keywords.
* webcam html5
* webar
* artoolkit web
